[tool.poetry]
name = "rdc-video-bot"
version = "0.1.0"
description = ""
authors = ["Shargrove09 <scott7c1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
